### ISSUE TITLE
Після terraform apply -var-file=ireland.tfvars з'являється помилка

### ISSUE THREAD

**Issue by PiterRudyy** [lavrovvv/laurel#3]
Роблю на Ubuntu завантаженій на Windows 10

Після виконання terraform apply -var-file=ireland.tfvars та підтвердження yes відразу вискакує
 Enter a value: yes

aws_launch_template.example: Creating...
│ Error: InvalidLaunchTemplateName.AlreadyExistsException: Launch template name already in use.
│       status code: 400, request id: acd5115a-ce52-4225-befe-d55500d4fc67
│
│   with aws_launch_template.example,
│   on main.tf line 15, in resource "aws_launch_template" "example":
│   15: resource "aws_launch_template" "example" {
│

Є ідеї в чому проблема?

**Comment by lavrovvv** [comment]
Ідеї є, вже є існуючий launch template. Необхідно видалити існуючий руками тут: https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#LaunchTemplates:
У подальшому рекомендую використовувати `terraform destroy -var-file=ireland.tfvars` щоб видалити його
